version: '3.8'
services:

  mysql:
    image: mysql:5.7
    container_name: mbs_mysql
    restart: always
    networks:
      - mbs-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql/data:/var/lib/mysql/
      - ./data/mysql/conf.d/:/etc/mysql/conf.d/
      - ./data/mysql/backup/:/backup/

  jira:
    build: ./jira
    container_name: mbs_jira
    environment:
      - TZ='Asia/Shanghai'
    restart: always
    networks:
      - mbs-net
    ports:
      - '8080:8080'
    volumes:
        - ./data/jira/var/:/var/atlassian/jira/
        - ./data/jira/logs/:/opt/atlassian/jira/logs/
    depends_on:
      - mysql

  confluence:
    build: ./confluence
    container_name: mbs_confluence
    environment:
      - TZ='Asia/Shanghai'
    restart: always
    networks:
      - mbs-net
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - ./data/confluence/var/:/var/atlassian/confluence/
      - ./data/confluence/logs/:/opt/atlassian/confluence/logs/
    depends_on:
      - mysql


networks:
  mbs-net:
    driver: bridge